import { FormEvent, useEffect, useState } from 'react';
import { Link2, Send, Shield, UserPlus } from 'lucide-react';
import { useSession } from '@/hooks/use-session';

type Invite = { id: number; name: string; claimedAt: string | null };
type LedgerGuest = { id: number; name: string; rsvp_status: string; payment: 'pending' | 'paid' | 'on_site' };
const paymentLabel = { pending: 'Pendente', paid: 'Pago', on_site: 'Paga no local' };

export default function Admin() {
  const { session } = useSession(); const [password, setPassword] = useState(() => sessionStorage.getItem('niver_admin_password') ?? '');
  const [title, setTitle] = useState('Recado do barco'), [body, setBody] = useState(''), [url, setUrl] = useState('/evento'), [status, setStatus] = useState('');
  const [inviteName, setInviteName] = useState(''), [inviteStatus, setInviteStatus] = useState(''), [lastCreatedUrl, setLastCreatedUrl] = useState(''), [invites, setInvites] = useState<Invite[]>([]);
  const [ledger, setLedger] = useState<LedgerGuest[]>([]), [reminderEnabled, setReminderEnabled] = useState(false), [surpriseName, setSurpriseName] = useState('');
  const headers = () => ({ 'Content-Type': 'application/json', ...(password ? { Authorization: `Bearer ${password}` } : {}), ...(session?.adminToken ? { 'X-Niver-Admin-Invite': session.adminToken } : {}) });
  const remember = () => password && sessionStorage.setItem('niver_admin_password', password);
  const load = async () => { const [a, b] = await Promise.all([fetch('/api/admin/invites', { headers: headers() }), fetch('/api/admin/payments', { headers: headers() })]); if (a.ok) setInvites(await a.json()); if (b.ok) { const data = await b.json(); setLedger(data.guests); setReminderEnabled(data.reminderEnabled); } };
  useEffect(() => { if (session?.isAdmin || password) void load(); }, []);
  const send = async (e: FormEvent) => { e.preventDefault(); setStatus('Enviando…'); const r = await fetch('/api/admin/notify', { method: 'POST', headers: headers(), body: JSON.stringify({ title, body, url }) }), d = await r.json(); if (!r.ok) return setStatus(d.error ?? 'Não foi possível enviar.'); remember(); setStatus(`Aviso salvo para ${d.saved} convidado(s). Push entregue em ${d.sent} aparelho(s).`); };
  const createInvite = async (e: FormEvent) => { e.preventDefault(); const r = await fetch('/api/admin/invites', { method: 'POST', headers: headers(), body: JSON.stringify({ name: inviteName }) }), d = await r.json(); if (!r.ok) return setInviteStatus(d.error ?? 'Não foi possível criar.'); remember(); setInviteName(''); setLastCreatedUrl(d.url); await navigator.clipboard?.writeText(d.url); setInviteStatus(`Convite de ${d.name} criado e copiado.`); await load(); };
  const setPayment = async (id: number, payment: LedgerGuest['payment']) => { const r = await fetch(`/api/admin/payments/${id}`, { method: 'PATCH', headers: headers(), body: JSON.stringify({ status: payment }) }); if (r.ok) setLedger(xs => xs.map(x => x.id === id ? { ...x, payment } : x)); };
  const addSurprise = async (e: FormEvent) => { e.preventDefault(); const r = await fetch('/api/admin/surprise-guests', { method: 'POST', headers: headers(), body: JSON.stringify({ name: surpriseName, payment: 'pending' }) }), d = await r.json(); if (!r.ok) return setStatus(d.error ?? 'Não foi possível adicionar.'); setSurpriseName(''); setLedger(xs => [...xs, d]); };
  const toggleReminder = async () => { const enabled = !reminderEnabled; const r = await fetch('/api/admin/payment-reminder', { method: 'PATCH', headers: headers(), body: JSON.stringify({ enabled, guestId: session?.id }) }); if (r.ok) setReminderEnabled(enabled); };
  const canUseAdmin = Boolean(session?.isAdmin || password);
  return <div className="panel-enter mx-auto max-w-xl space-y-6 pb-24"><section><p className="text-xs font-semibold uppercase tracking-[.2em] text-primary">Cabine do capitão</p><h1 className="mt-2 flex items-center gap-2 text-3xl font-display font-bold"><Shield className="h-6 w-6 text-primary"/>Administração</h1><p className="mt-2 text-sm text-muted-foreground">Operação do barco, sem expor dados da tripulação.</p></section>
    {!session?.isAdmin && <div className="glass-card rounded-2xl p-4"><label className="block text-sm font-medium">Senha administrativa<input value={password} onChange={e=>setPassword(e.target.value)} type="password" className="mt-2 h-11 w-full rounded-xl border border-white/15 bg-black/30 px-3 text-foreground" /></label><button type="button" onClick={() => { remember(); void load(); }} className="mt-3 h-10 rounded-xl border border-white/15 px-4 text-sm text-primary">Entrar no painel</button></div>}
    {canUseAdmin && <><section className="glass-card space-y-4 rounded-3xl p-5 sm:p-7"><div><h2 className="font-display text-xl font-bold">Contribuições</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">Só você vê este controle. RSVP e pagamento são independentes.</p></div><div className="flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-emerald-400/10 px-3 py-1 text-emerald-200">{ledger.filter(x=>x.payment==='paid').length} pagos</span><span className="rounded-full bg-amber-300/10 px-3 py-1 text-amber-100">{ledger.filter(x=>x.payment==='on_site').length} no local</span><span className="rounded-full bg-white/5 px-3 py-1 text-muted-foreground">{ledger.filter(x=>x.payment==='pending').length} pendentes</span></div><form onSubmit={addSurprise} className="rounded-2xl border border-white/10 bg-black/15 p-3"><p className="mb-2 text-sm font-medium">Chegou de surpresa?</p><div className="flex gap-2"><input value={surpriseName} onChange={e=>setSurpriseName(e.target.value)} required placeholder="Nome" className="h-10 min-w-0 flex-1 rounded-xl border border-white/15 bg-black/30 px-3 text-sm"/><button className="inline-flex h-10 items-center rounded-xl border border-primary/30 px-3 text-primary"><UserPlus className="h-4 w-4"/></button></div></form><div className="space-y-2">{ledger.map(g => <div key={g.id} className="rounded-2xl border border-white/10 bg-black/15 p-3"><div className="flex items-center justify-between gap-2"><span className="truncate text-sm font-semibold">{g.name}</span><span className="text-xs text-muted-foreground">{g.rsvp_status === 'going' ? 'vou' : g.rsvp_status}</span></div><div className="mt-2 grid grid-cols-3 gap-1">{(['paid','on_site','pending'] as const).map(v => <button key={v} onClick={() => void setPayment(g.id, v)} className={`min-h-9 rounded-lg border px-1 text-[10px] ${g.payment === v ? 'border-primary/60 bg-primary/15 text-primary' : 'border-white/10 text-muted-foreground'}`}>{paymentLabel[v]}</button>)}</div></div>)}</div></section>
    <section className="glass-card rounded-3xl p-5 sm:p-7"><div className="flex items-start justify-between gap-4"><div><h2 className="font-display text-xl font-bold">Lembrete de contribuição</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">Desligado por padrão. Quando você ligar, a pessoa vê um aviso leve e pode fechar sem bloquear nada.</p></div><button onClick={() => void toggleReminder()} className={`min-h-10 rounded-xl border px-3 text-sm font-semibold ${reminderEnabled ? 'border-emerald-300/40 bg-emerald-400/10 text-emerald-100' : 'border-white/15 text-muted-foreground'}`}>{reminderEnabled ? 'Ativo' : 'Desligado'}</button></div></section>
    <section className="glass-card space-y-4 rounded-3xl p-5 sm:p-7"><h2 className="font-display text-xl font-bold">Convite individual</h2><form onSubmit={createInvite} className="flex gap-2"><input value={inviteName} onChange={e=>setInviteName(e.target.value)} required maxLength={80} placeholder="Nome do convidado" className="h-11 min-w-0 flex-1 rounded-xl border border-white/15 bg-black/30 px-3 text-foreground"/><button className="premium-cta shimmer inline-flex h-11 shrink-0 items-center rounded-xl border border-[#fff0b4]/60 bg-gradient-to-r from-[#ffe399] via-[#efbd4f] to-[#c87520] px-4 font-bold text-[#150d05]"><Link2 className="mr-2 h-4 w-4"/>Gerar</button></form>{inviteStatus && <p className="rounded-xl border border-primary/20 bg-primary/10 p-3 text-sm text-primary">{inviteStatus}</p>}{lastCreatedUrl && <code className="block truncate rounded-xl border border-white/10 bg-black/25 p-3 text-xs text-[#ffe39a]">{lastCreatedUrl}</code>}{invites.map(i=><p key={i.id} className="text-sm">{i.name} <span className="text-muted-foreground">· {i.claimedAt ? 'abriu' : 'aguardando'}</span></p>)}</section>
    <form onSubmit={send} className="glass-card space-y-5 rounded-3xl p-5 sm:p-7"><h2 className="font-display text-xl font-bold">Notificações</h2><label className="block text-sm font-medium">Título<input value={title} onChange={e=>setTitle(e.target.value)} required maxLength={80} className="mt-2 h-11 w-full rounded-xl border border-white/15 bg-black/30 px-3 text-foreground" /></label><label className="block text-sm font-medium">Mensagem<textarea value={body} onChange={e=>setBody(e.target.value)} required maxLength={240} className="mt-2 min-h-28 w-full rounded-xl border border-white/15 bg-black/30 p-3 text-foreground" /></label><label className="block text-sm font-medium">Abrir ao tocar<input value={url} onChange={e=>setUrl(e.target.value)} required className="mt-2 h-11 w-full rounded-xl border border-white/15 bg-black/30 px-3 text-foreground" /></label><button className="premium-cta shimmer flex h-12 w-full items-center justify-center rounded-xl border border-[#fff0b4]/60 bg-gradient-to-r from-[#ffe399] via-[#efbd4f] to-[#c87520] font-bold text-[#150d05]"><Send className="mr-2 h-4 w-4" />Enviar notificação</button>{status && <p className="rounded-xl border border-primary/20 bg-primary/10 p-3 text-sm text-primary">{status}</p>}</form></>}</div>;
}
